{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.host }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  domains:
    - {{ .Values.ingress.host }}
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    {{- if .Values.ingress.host }}
    networking.gke.io/managed-certificates: {{ include "backend.fullname" . }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: {{ include "backend.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}
