{{- if .Values.backend.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dopp.fullname" . }}-api-key
  labels:
    {{- include "dopp.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.backend.apiKey | quote }}
{{- end }}
